# The docs say you should do <maj>.<min>.<BUILD>, and you should,

# This is a garbage version
version: '0.1.{build}'

# This resets the version programmatically
init:
 - ps: scripts\update-appveyor-version.ps1

branches:
  only:
    - master

#skip_non_tags: true

skip_commits:
  files:
    - 'docs/*'
    - '**/*.html'
    - '**/*.md'

max_jobs: 1

image: Visual Studios 2019

clone_folder: C:\projects\zic

shallow_clone: true

cache:
  - jar -> target/uberjar/*.jar
  - exe -> target/native-image/*.exe

install:
- cmd: >-
    call scripts\winbuild.bat
    clj -T:build native-image