#!/bin/sh
root_path=${PWD}

name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')

# https://www.graalvm.org/22.0/reference-manual/native-image/Agent/
native-image \
    --verbose \
    --enable-url-protocols=file,https,http \
    --report-unsupported-elements-at-runtime \
    --no-fallback \
    --enable-all-security-services \
    --no-server \
    --report-unsupported-elements-at-runtime \
    --initialize-at-build-time \
    --static \
    --libc=musl \
    -H:+ReportExceptionStackTraces \
    -H:+JNI \
    -H:Name="${name}" \
    -jar target/uberjar/${name}-${version}-standalone.jar \
    --initialize-at-build-time=buddy.util \
    --initialize-at-build-time=cheshire \
    --initialize-at-build-time=cheshire.generate \
    --initialize-at-build-time=cheshire.prettyprint \
    --initialize-at-build-time=clj_http.lite \
    --initialize-at-build-time=clojure.asm \
    --initialize-at-build-time=clojure.asm.commons \
    --initialize-at-build-time=clojure \
    --initialize-at-build-time=clojure.core \
    --initialize-at-build-time=clojure.core.protocols \
    --initialize-at-build-time=clojure.core.proxy$clojure.lang \
    --initialize-at-build-time=clojure.core.proxy$java.io \
    --initialize-at-build-time=clojure.core.reducers \
    --initialize-at-build-time=clojure.data \
    --initialize-at-build-time=clojure.inspector.proxy$java.lang \
    --initialize-at-build-time=clojure.inspector.proxy$javax.swing.table \
    --initialize-at-build-time=clojure.instant.proxy$java.lang \
    --initialize-at-build-time=clojure.java.api \
    --initialize-at-build-time=clojure.java.browse_ui.proxy$java.lang \
    --initialize-at-build-time=clojure.java \
    --initialize-at-build-time=clojure.java.io \
    --initialize-at-build-time=clojure.lang \
    --initialize-at-build-time=clojure.pprint \
    --initialize-at-build-time=clojure.pprint.proxy$java.io \
    --initialize-at-build-time=clojure.reflect \
    --initialize-at-build-time=clojure.reflect.proxy$clojure.asm \
    --initialize-at-build-time=clojure.repl.proxy$java.io \
    --initialize-at-build-time=clojure.repl.proxy$java.lang \
    --initialize-at-build-time=clojure.spec.alpha \
    --initialize-at-build-time=clojure.spec \
    --initialize-at-build-time=clojure.spec.gen \
    --initialize-at-build-time=clojure.spec.test \
    --initialize-at-build-time=clojure.test \
    --initialize-at-build-time=clojure.tools \
    --initialize-at-build-time=clojure.tools.logging \
    --initialize-at-build-time=clojure.tools.logging.impl \
    --initialize-at-build-time=clojure.tools.logging.proxy$java.io \
    --initialize-at-build-time=clojure.xml.proxy$java.lang \
    --initialize-at-build-time=com.fasterxml.jackson.core.async \
    --initialize-at-build-time=com.fasterxml.jackson.core.base \
    --initialize-at-build-time=com.fasterxml.jackson.core \
    --initialize-at-build-time=com.fasterxml.jackson.core.exc \
    --initialize-at-build-time=com.fasterxml.jackson.core.filter \
    --initialize-at-build-time=com.fasterxml.jackson.core.format \
    --initialize-at-build-time=com.fasterxml.jackson.core.io \
    --initialize-at-build-time=com.fasterxml.jackson.core.json.async \
    --initialize-at-build-time=com.fasterxml.jackson.core.json \
    --initialize-at-build-time=com.fasterxml.jackson.core.sym \
    --initialize-at-build-time=com.fasterxml.jackson.core.type \
    --initialize-at-build-time=com.fasterxml.jackson.core.util \
    --initialize-at-build-time=com.fasterxml.jackson.dataformat.cbor \
    --initialize-at-build-time=com.fasterxml.jackson.dataformat.cbor.databind \
    --initialize-at-build-time=com.fasterxml.jackson.dataformat.smile.async \
    --initialize-at-build-time=com.fasterxml.jackson.dataformat.smile \
    --initialize-at-build-time=com.fasterxml.jackson.dataformat.smile.databind \
    --initialize-at-build-time=jks_example$fn__1422.class \
    --initialize-at-build-time=jks_example$loading__6789__auto____1420.class \
    --initialize-at-build-time=jks_example$make_ssl_context.class \
    --initialize-at-build-time=module-info.class \
    --initialize-at-build-time=next \
    --initialize-at-build-time=next.jdbc \
    --initialize-at-build-time=next.jdbc.prepare \
    --initialize-at-build-time=next.jdbc.protocols \
    --initialize-at-build-time=next.jdbc.result_set \
    --initialize-at-build-time=onecli \
    --initialize-at-build-time=org.apache.commons.codec.binary \
    --initialize-at-build-time=org.apache.commons.codec \
    --initialize-at-build-time=org.apache.commons.codec.cli \
    --initialize-at-build-time=org.apache.commons.codec.digest \
    --initialize-at-build-time=org.apache.commons.codec.language.bm \
    --initialize-at-build-time=org.apache.commons.codec.language \
    --initialize-at-build-time=org.apache.commons.codec.net \
    --initialize-at-build-time=org.writequit.tigris \
    --initialize-at-build-time=serovers \
    --initialize-at-build-time=serovers.core \
    --initialize-at-build-time=slingshot \
    --initialize-at-build-time=zic \
    --initialize-at-build-time=zic.session \
    -H:+AllowIncompleteClasspath \
    -J-Dclojure.compiler.direct-linking=true \
    -J-Dclojure.spec.skip-macros=true \
    -J-Xmx4G

#org.h2.api
#org.h2.bnf
#org.h2.bnf.context
#org.h2
#org.h2.command
#org.h2.command.ddl
#org.h2.command.dml
#org.h2.compress
#org.h2.constraint
#org.h2.engine
#org.h2.expression
#org.h2.fulltext
#org.h2.index
#org.h2.jdbc
#org.h2.jdbcx
#org.h2.jmx
#org.h2.message
#org.h2.mvstore.cache
#org.h2.mvstore
#org.h2.mvstore.db
#org.h2.mvstore.rtree
#org.h2.mvstore.type
#org.h2.result
#org.h2.schema
#org.h2.security
#org.h2.server
#org.h2.server.pg
#org.h2.server.web
#org.h2.store
#org.h2.store.fs
#org.h2.table
#org.h2.tools
#org.h2.upgrade
#org.h2.util
#org.h2.value
#org.bouncycastle.asn1.anssi
#org.bouncycastle.asn1.bc
#org.bouncycastle.asn1.bsi
#org.bouncycastle.asn1
#org.bouncycastle.asn1.cmc
#org.bouncycastle.asn1.cmp
#org.bouncycastle.asn1.cms
#org.bouncycastle.asn1.cms.ecc
#org.bouncycastle.asn1.crmf
#org.bouncycastle.asn1.cryptlib
#org.bouncycastle.asn1.cryptopro
#org.bouncycastle.asn1.dvcs
#org.bouncycastle.asn1.eac
#org.bouncycastle.asn1.edec
#org.bouncycastle.asn1.esf
#org.bouncycastle.asn1.ess
#org.bouncycastle.asn1.est
#org.bouncycastle.asn1.gm
#org.bouncycastle.asn1.gnu
#org.bouncycastle.asn1.iana
#org.bouncycastle.asn1.icao
#org.bouncycastle.asn1.isara
#org.bouncycastle.asn1.isismtt
#org.bouncycastle.asn1.isismtt.ocsp
#org.bouncycastle.asn1.isismtt.x509
#org.bouncycastle.asn1.iso
#org.bouncycastle.asn1.kisa
#org.bouncycastle.asn1.microsoft
#org.bouncycastle.asn1.misc
#org.bouncycastle.asn1.mozilla
#org.bouncycastle.asn1.nist
#org.bouncycastle.asn1.nsri
#org.bouncycastle.asn1.ntt
#org.bouncycastle.asn1.ocsp
#org.bouncycastle.asn1.oiw
#org.bouncycastle.asn1.pkcs
#org.bouncycastle.asn1.rosstandart
#org.bouncycastle.asn1.sec
#org.bouncycastle.asn1.smime
#org.bouncycastle.asn1.teletrust
#org.bouncycastle.asn1.tsp
#org.bouncycastle.asn1.ua
#org.bouncycastle.asn1.util
#org.bouncycastle.asn1.x500
#org.bouncycastle.asn1.x500.style
#org.bouncycastle.asn1.x509
#org.bouncycastle.asn1.x509.qualified
#org.bouncycastle.asn1.x509.sigi
#org.bouncycastle.asn1.x9
#org.bouncycastle.cert.bc
#org.bouncycastle.cert
#org.bouncycastle.cert.cmp
#org.bouncycastle.cert.crmf.bc
#org.bouncycastle.cert.crmf
#org.bouncycastle.cert.crmf.jcajce
#org.bouncycastle.cert.dane
#org.bouncycastle.cert.dane.fetcher
#org.bouncycastle.cert.jcajce
#org.bouncycastle.cert.ocsp
#org.bouncycastle.cert.ocsp.jcajce
#org.bouncycastle.cert.path
#org.bouncycastle.cert.path.validations
#org.bouncycastle.cert.selector
#org.bouncycastle.cert.selector.jcajce
#org.bouncycastle
#org.bouncycastle.cmc
#org.bouncycastle.cms.bc
#org.bouncycastle.cms
#org.bouncycastle.cms.jcajce
#org.bouncycastle.crypto.agreement
#org.bouncycastle.crypto.agreement.jpake
#org.bouncycastle.crypto.agreement.kdf
#org.bouncycastle.crypto.agreement.srp
#org.bouncycastle.crypto
#org.bouncycastle.crypto.commitments
#org.bouncycastle.crypto.digests
#org.bouncycastle.crypto.ec
#org.bouncycastle.crypto.encodings
#org.bouncycastle.crypto.engines
#org.bouncycastle.crypto.examples
#org.bouncycastle.crypto.generators
#org.bouncycastle.crypto.io
#org.bouncycastle.crypto.kems
#org.bouncycastle.crypto.macs
#org.bouncycastle.crypto.modes
#org.bouncycastle.crypto.modes.gcm
#org.bouncycastle.crypto.modes.kgcm
#org.bouncycastle.crypto.paddings
#org.bouncycastle.crypto.params
#org.bouncycastle.crypto.parsers
#org.bouncycastle.crypto.prng
#org.bouncycastle.crypto.prng.drbg
#org.bouncycastle.crypto.signers
#org.bouncycastle.crypto.util
#org.bouncycastle.dvcs
#org.bouncycastle.eac
#org.bouncycastle.eac.jcajce
#org.bouncycastle.eac.operator
#org.bouncycastle.eac.operator.jcajce
#org.bouncycastle.est
#org.bouncycastle.est.jcajce
#org.bouncycastle.i18n
#org.bouncycastle.i18n.filter
#org.bouncycastle.iana
#org.bouncycastle.its.asn1
#org.bouncycastle.jcajce
#org.bouncycastle.jcajce.interfaces
#org.bouncycastle.jcajce.io
#org.bouncycastle.jcajce.provider.asymmetric
#org.bouncycastle.jcajce.provider.asymmetric.dh
#org.bouncycastle.jcajce.provider.asymmetric.dsa
#org.bouncycastle.jcajce.provider.asymmetric.dstu
#org.bouncycastle.jcajce.provider.asymmetric.ec
#org.bouncycastle.jcajce.provider.asymmetric.ecgost12
#org.bouncycastle.jcajce.provider.asymmetric.ecgost
#org.bouncycastle.jcajce.provider.asymmetric.edec
#org.bouncycastle.jcajce.provider.asymmetric.elgamal
#org.bouncycastle.jcajce.provider.asymmetric.gost
#org.bouncycastle.jcajce.provider.asymmetric.ies
#org.bouncycastle.jcajce.provider.asymmetric.rsa
#org.bouncycastle.jcajce.provider.asymmetric.util
#org.bouncycastle.jcajce.provider.asymmetric.x509
#org.bouncycastle.jcajce.provider.config
#org.bouncycastle.jcajce.provider.digest
#org.bouncycastle.jcajce.provider.drbg
#org.bouncycastle.jcajce.provider.keystore.bc
#org.bouncycastle.jcajce.provider.keystore.bcfks
#org.bouncycastle.jcajce.provider.keystore
#org.bouncycastle.jcajce.provider.keystore.pkcs12
#org.bouncycastle.jcajce.provider.symmetric
#org.bouncycastle.jcajce.provider.symmetric.util
#org.bouncycastle.jcajce.provider.util
#org.bouncycastle.jcajce.spec
#org.bouncycastle.jcajce.util
#org.bouncycastle.jce
#org.bouncycastle.jce.exception
#org.bouncycastle.jce.interfaces
#org.bouncycastle.jce.netscape
#org.bouncycastle.jce.provider
#org.bouncycastle.jce.spec
#org.bouncycastle.math
#org.bouncycastle.math.ec
#org.bouncycastle.math.ec.custom.djb
#org.bouncycastle.math.ec.custom.gm
#org.bouncycastle.math.ec.custom.sec
#org.bouncycastle.math.ec.endo
#org.bouncycastle.math.ec.rfc7748
#org.bouncycastle.math.ec.rfc8032
#org.bouncycastle.math.ec.tools
#org.bouncycastle.math.field
#org.bouncycastle.math.raw
#org.bouncycastle.mime
#org.bouncycastle.mime.encoding
#org.bouncycastle.mime.smime
#org.bouncycastle.mozilla
#org.bouncycastle.mozilla.jcajce
#org.bouncycastle.openssl.bc
#org.bouncycastle.openssl
#org.bouncycastle.openssl.jcajce
#org.bouncycastle.operator.bc
#org.bouncycastle.operator
#org.bouncycastle.operator.jcajce
#org.bouncycastle.pkcs.bc
#org.bouncycastle.pkcs
#org.bouncycastle.pkcs.jcajce
#org.bouncycastle.pkix
#org.bouncycastle.pkix.jcajce
#org.bouncycastle.pqc.asn1
#org.bouncycastle.pqc.crypto
#org.bouncycastle.pqc.crypto.gmss
#org.bouncycastle.pqc.crypto.gmss.util
#org.bouncycastle.pqc.crypto.lms
#org.bouncycastle.pqc.crypto.mceliece
#org.bouncycastle.pqc.crypto.newhope
#org.bouncycastle.pqc.crypto.qtesla
#org.bouncycastle.pqc.crypto.rainbow
#org.bouncycastle.pqc.crypto.rainbow.util
#org.bouncycastle.pqc.crypto.sphincs
#org.bouncycastle.pqc.crypto.util
#org.bouncycastle.pqc.crypto.xmss
#org.bouncycastle.pqc.jcajce.interfaces
#org.bouncycastle.pqc.jcajce.provider
#org.bouncycastle.pqc.jcajce.provider.gmss
#org.bouncycastle.pqc.jcajce.provider.lms
#org.bouncycastle.pqc.jcajce.provider.mceliece
#org.bouncycastle.pqc.jcajce.provider.newhope
#org.bouncycastle.pqc.jcajce.provider.qtesla
#org.bouncycastle.pqc.jcajce.provider.rainbow
#org.bouncycastle.pqc.jcajce.provider.sphincs
#org.bouncycastle.pqc.jcajce.provider.util
#org.bouncycastle.pqc.jcajce.provider.xmss
#org.bouncycastle.pqc.jcajce.spec
#org.bouncycastle.pqc.math.linearalgebra
#org.bouncycastle.tsp
#org.bouncycastle.tsp.cms
#org.bouncycastle.util
#org.bouncycastle.util.encoders
#org.bouncycastle.util.io
#org.bouncycastle.util.io.pem
#org.bouncycastle.util.test
#org.bouncycastle.voms
#org.bouncycastle.x509
#org.bouncycastle.x509.extension
#org.bouncycastle.x509.util
