#!/bin/sh

if [ ! -f "project.clj" ]
then
    echo "This script must be run from the root of the project." >&2
    usage
fi

root_path=${PWD}

name=$(scripts/name)
version=$(scripts/version)

packages=$(${root_path}/scripts/get-all-uberjar-packages |
    cat - "${root_path}/build/loaded-packages" | sort -u)
num_packages=$(printf '%s' "${packages}" | wc -l)
echo "Recognized ${num_packages} packages"
sleep 2

# https://www.graalvm.org/22.0/reference-manual/native-image/Agent/
#-H:+AllowIncompleteClasspath \
#https://groups.google.com/g/h2-database/c/xWaIXbqIgqA
# https://github.com/oracle/graal/issues/3398

#--static \
#--no-fallback \
#--libc=musl \
#-H:CCompilerOption=-Wl,-z,stack-size=2097152 \
#--link-at-build-time \
verbatim="
--verbose \
--enable-url-protocols=https,http \
--report-unsupported-elements-at-runtime \
--install-exit-handlers \
-H:+ReportExceptionStackTraces \
-H:+PrintClassInitialization \
-Dfile.encoding=UTF-8 \
-J-Dclojure.compiler.direct-linking=true \
-J-Dclojure.spec.skip-macros=true \
-H:-CheckToolchain \
-H:+InlineBeforeAnalysis \
-H:Log=registerResource: \
-H:IncludeResources=.*/org/sqlite/.*|org/sqlite/.*|.*/sqlite-jdbc.properties \
-H:+JNI \
-H:Name=${name} \
-jar target/uberjar/${name}-${version}-standalone.jar \
-J-Xmx4G"

exceptions="\
"
#org.h2.util.JdbcUtils \
#org.h2.engine.ConnectionInfo \
#org.h2.engine.Engine \
#org.h2.engine.SysProperties \
#org.h2.util.MathUtils \
#org.h2.value.DataType \
#org.h2.value.ValueGeometry \
#org.h2.mvstore.db.MVTable \
#org.h2.result.SortOrder \
#org.h2.mvstore.db.MVPrimaryIndex \
#org.h2.engine.Mode \
#org.h2.value.ValueLong \
#org.h2.util.MemoryUnmapper
#"
#exceptions=""
for i in ${verbatim}
do
    arguments="${arguments} ${i}"
done
for i in ${packages}
do
    arguments="${arguments} --initialize-at-build-time=${i}"
done
for i in ${exceptions}
do
    arguments="${arguments} --initialize-at-run-time=${i}"
done
native-image ${arguments} "${@}"
