#!/bin/sh

if [ ! -f "deps.edn" ]
then
    echo "This script must be run from the root of the project." >&2
    exit 1
fi

root_path=${PWD}

name=$(scripts/name)
version=$(scripts/version)


jar -tf "${root_path}/target/${name}-${version}-standalone.jar" |
    grep -E '\.class$' |
    sed -e 's|/[^/]\{1,\}[.]class$|/.class|g' |
    grep -v -E '^META-INF' |
    grep -v -E '^classes' |
    sort -u |
    sed -e 's|/[.]class$||g' \
        -e 's|[/]|.|g'
grep -r -E '\(java\.' src | sed -e 's|^.\{1,\}java|java|g' -e 's|[.][A-Z].*$||g'
echo 'java.lang'
echo 'java.math'
echo 'java.lang.reflect'
echo 'java.util'
